<?php
$directLoginLink = null;
if ((Mage::getStoreConfig('awonpulse/general/credurlkey')) && (Mage::getStoreConfig('awonpulse/general/credhash'))) {
    $credurlkey = Mage::getStoreConfig('awonpulse/general/credurlkey');
    $credhash = Mage::getStoreConfig('awonpulse/general/credhash');
    $qrsrc = 'http://chart.apis.google.com/chart?chs=250x250&cht=qr&chld=1/1&choe=utf-8&chl=';
    $backUrl = Mage::app()->getDefaultStoreView()->getBaseUrl() . md5($credurlkey . $credhash);
    $qrsrc .= 'http://m.onpulse.info/?qrhash=' . base64_encode($backUrl);
    $directLoginLink = 'http://m.onpulse.info/?qrhash=' . base64_encode($backUrl);
} else {
    $credurlkey = '';
    $credhash = '';
    $qrsrc = null;
}
?>

<table class="form-list">
    <tbody>
    <form method="post">
        <tr>
            <td class="label">
                <label><?php echo Mage::helper('awonpulse')->__('URL') ?></label>
            </td>
            <td class="value">
                <input class="input-text" style="width: 600px;" onclick="this.select()" type="text" readonly="readonly"
                       name="groups[general][fields][credurlkey][value]" id="urlkey"
                       value="<?php echo Mage::app()->getDefaultStoreView()->getBaseUrl() . $credurlkey;?>">

                <p class="note">
                    <span><?php echo Mage::helper('awonpulse')->__('Your login name to access OnPulse service') ?></span>
                </p>
            </td>
        </tr>
        <tr>
            <td class="label">
                <label><?php echo Mage::helper('awonpulse')->__('Key') ?></label>
            </td>
            <td class="value">
                <input class="input-text" style="width: 600px;" type="text" onclick="this.select()" readonly="readonly"
                       name="groups[general][fields][credhash][value]" id="hash" value="<?php echo $credhash;?>">
            </td>
        </tr>
        <?php if ($directLoginLink) : ?>
        <tr>
            <td class="label">
                <label><?php echo Mage::helper('awonpulse')->__('Direct login URL') ?></label>
            </td>
            <td style="padding-left: 6px; ">
                <a href="<?php echo $directLoginLink;?>" style="display: block; width: 600px; padding-top: 5px;"
                   target="_blank"><?php echo substr($directLoginLink, 0, 80) . '...'; ?></a>
            </td>
        </tr>
        <?php endif; ?>
        <?php if ($qrsrc) : ?>
        <tr>
            <td class="label">
                <label><?php echo Mage::helper('awonpulse')->__('Direct login QR') ?></label>
            </td>
            <td>
                <br/>&nbsp;&nbsp;<img src="<?php echo $qrsrc; ?>">
            </td>
        </tr>
        <?php endif; ?>
        <tr>
            <td>
            </td>
            <td style="padding-left: 6px; padding-top: 10px;">
                <button onclick="generate(this);"><?php echo Mage::helper('awonpulse')->__('Create new login credentials') ?></button>
                <p class="note">
                    <span><?php echo Mage::helper('awonpulse')->__('Each time you reset credentials OnPulse generates new URL, key, direct login and QR code') ?></span>
                </p>
            </td>
        </tr>
    </form>
    </tbody>
</table>


<script type="text/javascript">
    var flagSubmit = false;
    function generate() {
        if (!flagSubmit) {
            key = mkPass(8);
            hash = mkPass(8);
            document.getElementById('urlkey').value = key;
            document.getElementById('hash').value = hash;
            flagSubmit = true;
        }
    }

    function mtRand(min, max) {
        var range = max - min + 1;
        var n = Math.floor(Math.random() * range) + min;
        return n;
    }

    function mkPass(len) {
        var len = 8;
        var pass = '';
        var rnd = 0;
        var c = '';
        for (i = 0; i < len; i++) {
            rnd = mtRand(0, 1); // Латиница или цифры
            if (rnd == 0) {
                c = String.fromCharCode(mtRand(48, 57));
            }
            if (rnd == 1) {
                c = String.fromCharCode(mtRand(97, 122));
            }
            pass += c;
        }
        return pass;
    }

    document.getElementsByClassName('form-buttons')[0].style.display = 'none';
    document.getElementsByClassName('form-buttons')[1].style.display = 'none';


</script>
